language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
env:
  global:
  - APP_UUID=398ea708-50eb-499f-98d3-14cc7692668c
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
before_install:
  - export APP_PRIVATE_KEY=$(cat travis/fake_private_key_for_testing)
script: sbt ++$TRAVIS_SCALA_VERSION test

deploy:
  - provider: script
    script: sbt ++$TRAVIS_SCALA_VERSION clean publish
    on:
      branch: develop
