language: scala
scala:
- 2.12.5
jdk:
- oraclejdk8
services:
  - docker
env:
  global:
  - APP_MAUTH_UUID=398ea708-50eb-499f-98d3-14cc7692668c
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
before_install:
- export APP_MAUTH_PRIVATE_KEY=$(cat travis/fake_private_key_for_testing)
- echo -e "machine github.com\n  login $GITHUB_AUTH_TOKEN" >> ~/.netrc
script: sbt ++$TRAVIS_SCALA_VERSION test
deploy:
- provider: script
  script: travis/deploy.sh
  on:
    all_branches: true
    tags: false
- provider: script
  script: sbt mauth-proxy/ecr:push
  on:
    all_branches: true
    tags: false
