language: java
jdk:
- oraclejdk8
env:
  global:
  - APP_UUID=398ea708-50eb-499f-98d3-14cc7692668c
 cache:
  directories:
  - $HOME/.m2
before_install:
 - export APP_PRIVATE_KEY=$(cat travis/fake_private_key_for_testing)
install: mvn install -Dmaven.javadoc.skip=true -B -V --settings travis/settings.xml
script: mvn test --settings travis/settings.xml

deploy:
  provider: script
  script: mvn deploy -DskipTests=true --settings travis/settings.xml
  on:
    branch: develop
